version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-sandbox
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb01
    ports:
      - "5432:5432"
    volumes:
      - postgres-sandbox:/var/lib/postgresql/data
      # - ./postgres/initdb.d:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4:6.11
    container_name: pgadmin-sandbox
    ports:
      - 8080:80
    volumes:
      - pgadmin-sandbox:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres

volumes:
  postgres-sandbox:
    name: vpg
  pgadmin-sandbox:
    name: vpga
